Repository mne-tools/mne-python, pull requests merged in 2019-10, with the labels that each got.

#6866 Fix TAL channel parsing for EDF-D files
  doc/changes/latest.inc
  mne/io/edf/edf.py
Labels: backport-candidate

#6927 FIX: Fix nave regression
  doc/changes/latest.inc
  mne/evoked.py
  mne/tests/test_evoked.py
Labels: BUG, backport-candidate

#6731 MRG: Use _Brain in plot_source_estimates
  .circleci/config.yml
  environment.yml
  examples/visualization/plot_xhemi.py
  mne/viz/_3d.py
  mne/viz/_brain/_brain.py
  mne/viz/_brain/colormap.py
  mne/viz/_brain/tests/test_brain.py
  mne/viz/_brain/utils.py
  mne/viz/_brain/view.py
  mne/viz/backends/_pysurfer_mayavi.py
  mne/viz/backends/_pyvista.py
  mne/viz/backends/base_renderer.py
  mne/viz/backends/renderer.py
  mne/viz/backends/tests/test_renderer.py
  mne/viz/tests/test_3d.py
  requirements.txt
Labels: VIZ

#6930 FIX: Aligning frequency bins to y-axis
  doc/changes/latest.inc
  mne/viz/utils.py
Labels: backport-candidate

#6900 MRG, FIX: Corrmap check
  doc/changes/latest.inc
  mne/preprocessing/ica.py
  mne/preprocessing/tests/test_ica.py
Labels: backport-candidate

#6948 MRG, FIX: More complete test
  mne/preprocessing/ica.py
  mne/preprocessing/tests/test_ica.py
  tutorials/preprocessing/plot_40_artifact_correction_ica.py
Labels: backport-candidate

#6964 [MRG] Use latest version 0.22.4 of pyvista instead of master
  environment.yml
  requirements.txt
Labels: VIZ

#6972 [MRG] Fix borders on pyvista backend
  environment.yml
  examples/visualization/plot_publication_figure.py
  mne/viz/backends/_pyvista.py
  requirements.txt
Labels: BUG, VIZ

#6976 Fix ica.plot_properties with bad data
  mne/viz/ica.py
  mne/viz/utils.py
Labels: BUG

#6998 [MRG] Update 3d backend overview table
  mne/viz/backends/renderer.py
Labels: VIZ
