Repository mne-tools/mne-python, pull requests merged in 2019-05, with the labels that each got.

#6227 MRG: Power estimate for LCMV: apply_lcmv_cov
  doc/python_reference.rst
  doc/whats_new.rst
  mne/beamformer/__init__.py
  mne/beamformer/_compute_beamformer.py
  mne/beamformer/_dics.py
  mne/beamformer/_lcmv.py
  mne/beamformer/tests/test_external.py
Labels: Beamformer

#6305 MRG: Improve DICS example
  examples/inverse/plot_dics_source_power.py
Labels: Beamformer, DOC

#6350 MRG, API: Additional mne.realtime deprecations
  doc/conf.py
  doc/documentation.rst
  doc/python_reference.rst
  doc/whats_new.rst
  examples/realtime/README.txt
  examples/realtime/plot_compute_rt_average.py
  examples/realtime/plot_compute_rt_decoder.py
  examples/realtime/plot_ftclient_rt_average.py
  examples/realtime/plot_ftclient_rt_compute_psd.py
  examples/realtime/plot_lslclient_rt.py
  examples/realtime/plot_rt_feedback_server.py
  examples/realtime/rt_feedback_client.py
  mne/decoding/transformer.py
  mne/tests/test_docstring_parameters.py
Labels: backport-candidate
