Repository mne-tools/mne-python, pull requests merged in 2020-12, with the labels that each got.

#8576 MRG: Use overlay compositing
  examples/inverse/plot_source_space_snr.py
  mne/viz/_brain/__init__.py
  mne/viz/_brain/_brain.py
  mne/viz/_brain/_linkviewer.py
  mne/viz/_brain/callback.py
  mne/viz/_brain/tests/test_brain.py
  mne/viz/backends/_pyvista.py
Labels: VIZ

#8626 FIX: point_labels
  examples/connectivity/plot_sensor_connectivity.py
  mne/viz/backends/_pyvista.py
Labels: FIX

#8627 FIX: volume
  examples/inverse/plot_source_space_snr.py
  mne/viz/_brain/_brain.py
  tutorials/misc/plot_seeg.py
Labels: FIX

#8643 FIX: scalar_bar
  examples/inverse/plot_source_space_snr.py
  examples/inverse/plot_vector_mne_solution.py
  mne/viz/_brain/_brain.py
  mne/viz/backends/_pysurfer_mayavi.py
  mne/viz/backends/_pyvista.py
  mne/viz/backends/_utils.py
  mne/viz/backends/tests/test_renderer.py
  tutorials/misc/plot_seeg.py
  tutorials/source-modeling/plot_visualize_stc.py
Labels: FIX

#8657 FIX: notebook 3d backend
  mne/viz/backends/_notebook.py
Labels: FIX

#8676 MRG: Fix make_watershed_bem() docs
  mne/bem.py
Labels: DOC, backport-candidate

#8675 MRG, BUG: Fix bug with super versus eq in eSSS
  doc/changes/latest.inc
  mne/preprocessing/maxwell.py
  mne/preprocessing/tests/test_maxwell.py
Labels: backport-candidate
