Repository mne-tools/mne-python, pull requests merged in 2020-10, with the labels that each got.

#8341 MRG, BUG: Fix line color in ICA.plot_overlay
  doc/changes/latest.inc
  mne/viz/ica.py
Labels: BUG, VIZ, backport-candidate

#8344 MRG, BUG: Fix handling of axes with constrained_layout=True
  doc/changes/latest.inc
  mne/viz/tests/test_evoked.py
  mne/viz/utils.py
Labels: backport-candidate

#8350 MRG, BUG: Force keywords for verbose in short sigs
  doc/changes/latest.inc
  mne/epochs.py
  mne/evoked.py
  mne/utils/_logging.py
  mne/utils/docs.py
  mne/utils/tests/test_docs.py
Labels: backport-candidate

#8352 WIP: Merge time viewer code into Brain
  mne/icons/README.rst
  mne/viz/_3d.py
  mne/viz/_brain/__init__.py
  mne/viz/_brain/_brain.py
  mne/viz/_brain/_linkviewer.py
  mne/viz/_brain/_notebook.py
  mne/viz/_brain/_scraper.py
  mne/viz/_brain/_timeviewer.py
  mne/viz/_brain/mplcanvas.py
  mne/viz/_brain/tests/test_brain.py
Labels: VIZ

#8340 BUG: Split file issue on dashes
  doc/changes/latest.inc
  doc/changes/names.inc
  mne/io/fiff/tests/test_raw_fiff.py
  mne/io/open.py
Labels: backport-candidate

#8361 WIP: Fix bugs in Brain
  mne/viz/_3d.py
  mne/viz/_brain/_brain.py
  mne/viz/backends/_pyvista.py
Labels: VIZ, backport-candidate

#8372 MRG, DOC: Make clear which functions have been renamed
  doc/changes/0.21.inc
Labels: backport-candidate

#8371 MRG, DOC: Fix API documentation rendering in Webkit
  doc/_static/style.css
Labels: backport-candidate

#8368 WIP : rank was not passed to compute_depth_prior
  doc/changes/latest.inc
  mne/minimum_norm/inverse.py
Labels: backport-candidate

#8373 fixes for new sklearn
  mne/fixes.py
Labels: backport-candidate

#8393 MRG, BUG: Fix plot_alignment
  doc/changes/latest.inc
  mne/viz/_3d.py
  mne/viz/tests/test_3d.py
  tutorials/misc/plot_ecog.py
  tutorials/preprocessing/plot_70_fnirs_processing.py
Labels: backport-candidate

#8396 Add fix to give a proper error message when an unsupported Nihon Kohden file is read.
  mne/io/nihon/nihon.py
Labels: backport-candidate

#8405 FIX: focalpoint
  examples/visualization/plot_3d_to_2d.py
  mne/viz/backends/_pyvista.py
Labels: FIX, VIZ

#8408 FIX: separate MPL canvas
  mne/viz/_brain/_brain.py
Labels: FIX

#8409 ENH: Test separate MPL canvas in stc.plot
  mne/viz/_brain/tests/test_brain.py
  mne/viz/tests/test_3d.py
Labels: ENH

#8418 FIX: notebook attribute name
  mne/viz/_brain/tests/test.ipynb
Labels: FIX

#8434 [MRG] BUG: Fix BrainVision reading for certain vhdr files
  doc/changes/latest.inc
  mne/io/brainvision/brainvision.py
  mne/io/brainvision/tests/data/test.vhdr
  mne/io/brainvision/tests/test_brainvision.py
Labels: BUG, backport-candidate

#8435 [MRG] BUG: Do not allow baseline removal after preload
  doc/changes/latest.inc
  mne/epochs.py
  mne/tests/test_epochs.py
Labels: BUG, backport-candidate

#8416 MRG, BUG: Ensure channel entries are valid
  doc/changes/latest.inc
  mne/channels/tests/test_layout.py
  mne/io/meas_info.py
  mne/io/reference.py
  mne/io/tests/test_meas_info.py
  mne/io/tests/test_reference.py
  mne/preprocessing/ica.py
Labels: backport-candidate
