Repository mne-tools/mne-python, pull requests merged in 2020-09, with the labels that each got.

#8181 MRG: Split _timeviewer.py into multiple files
  mne/viz/_brain/__init__.py
  mne/viz/_brain/_linkviewer.py
  mne/viz/_brain/_timeviewer.py
  mne/viz/_brain/callback.py
  mne/viz/_brain/mplcanvas.py
  mne/viz/_brain/tests/test_brain.py
Labels: VIZ

#8182 MRG: Improve lighting in 3D viz
  mne/viz/_brain/_brain.py
  mne/viz/backends/_pyvista.py
Labels: VIZ

#8116 MRG: Recreate our helmet graphic
  examples/visualization/plot_mne_helmet.py
  mne/evoked.py
  mne/icons/mne_icon.png
  mne/viz/_3d.py
  mne/viz/_brain/_brain.py
  mne/viz/backends/_pysurfer_mayavi.py
  mne/viz/backends/_pyvista.py
  mne/viz/backends/base_renderer.py
  mne/viz/backends/renderer.py
Labels: VIZ

#8220 MRG: Set pyvista as default 3d backend
  doc/changes/latest.inc
  environment.yml
  mne/viz/backends/_utils.py
  requirements.txt
Labels: VIZ

#6017 Nihon Kohden EEG file reader WIP
  doc/conf.py
  doc/python_reference.rst
  mne/io/__init__.py
  mne/io/nihon/__init__.py
  mne/io/nihon/nihon.py
  mne/io/nihon/tests/test_nihon.py
Labels: Core

#8285 MRG, FIX: Fix single handling
  doc/changes/latest.inc
  mne/viz/_brain/_brain.py
  mne/viz/_brain/tests/test_brain.py
Labels: backport-candidate

#8283 Gracefully handle invalid EDF dates
  doc/changes/latest.inc
  doc/sphinxext/gh_substitutions.py
  mne/io/edf/edf.py
  mne/io/edf/tests/test_edf.py
Labels: backport-candidate

#8287 BUG: Fix version on landing page
  doc/_static/style.css
  doc/index.rst
  doc/overview/index.rst
Labels: backport-candidate

#8288 MRG, DOC: Improve memory
  tutorials/machine-learning/plot_sensors_decoding.py
Labels: backport-candidate

#8297 Sourcerank
  setup.py
Labels: backport-candidate

#8303 MRG, BUG: Fix add_reference_channels
  doc/changes/latest.inc
  mne/io/reference.py
  mne/io/tests/test_reference.py
Labels: backport-candidate

#8314 DOC: Make Brain public [circle front]
  doc/conf.py
  doc/python_reference.rst
  mne/tests/test_docstring_parameters.py
  mne/utils/docs.py
  mne/viz/_3d.py
  mne/viz/__init__.py
  mne/viz/_brain/__init__.py
  mne/viz/_brain/_brain.py
  mne/viz/_brain/_scraper.py
  mne/viz/_brain/_timeviewer.py
  mne/viz/_brain/tests/test_brain.py
  mne/viz/backends/renderer.py
Labels: backport-candidate

#8318 MRG, BUG: Fix comp + pick without preload
  doc/changes/latest.inc
  mne/channels/channels.py
  mne/io/tests/test_compensator.py
Labels: backport-candidate
