Repository mne-tools/mne-python, pull requests merged in 2021-07, with the labels that each got.

#9532 Improve sensor locations tutorial
  tutorials/intro/40_sensor_locations.py
Labels: DOC

#9537 Improve scalings description in Raw.plot()
  mne/viz/raw.py
Labels: DOC

#9564 FIX: brain RGBA screenshot
  doc/changes/latest.inc
  mne/viz/_brain/_brain.py
  mne/viz/_brain/tests/test_brain.py
  mne/viz/utils.py
Labels: FIX

#9555 Add get_data method to Evoked
  doc/changes/latest.inc
  mne/channels/tests/test_interpolation.py
  mne/evoked.py
  mne/io/tests/test_reference.py
  mne/tests/test_evoked.py
  setup.cfg
Labels: ENH

#9553 [MRG] Add `units` parameter to get_data for Epochs
  doc/changes/latest.inc
  mne/epochs.py
  mne/io/base.py
  mne/tests/test_epochs.py
  mne/utils/docs.py
Labels: ENH

#9556 [MRG] ENH, FIX: Add tmin/tmax parameters to get_data methods, fix bug in find_bads_ecg
  doc/changes/latest.inc
  mne/epochs.py
  mne/evoked.py
  mne/io/base.py
  mne/io/tests/test_raw.py
  mne/preprocessing/ecg.py
  mne/preprocessing/ica.py
  mne/preprocessing/tests/test_ica.py
  mne/rank.py
  mne/tests/test_epochs.py
  mne/tests/test_evoked.py
  mne/utils/check.py
Labels: ENH, FIX

#9570 add HPI SNR calculation and plotting
  doc/changes/latest.inc
  doc/preprocessing.rst
  doc/visualization.rst
  mne/chpi.py
  mne/tests/test_chpi.py
  mne/viz/__init__.py
  mne/viz/misc.py
  mne/viz/tests/test_misc.py
  tutorials/preprocessing/59_head_positions.py
Labels: ENH
