Repository mne-tools/mne-python, pull requests merged in 2021-03, with the labels that each got.

#8834 ENH: Allow automated compilation of metadata
  doc/changes/latest.inc
  doc/datasets.rst
  doc/events.rst
  doc/overview/datasets_index.rst
  doc/references.bib
  mne/datasets/__init__.py
  mne/datasets/erp_core/__init__.py
  mne/datasets/erp_core/erp_core.py
  mne/datasets/utils.py
  mne/epochs.py
  mne/tests/test_epochs.py
  mne/utils/config.py
  tools/circleci_download.sh
  tutorials/epochs/plot_40_autogenerate_metadata.py
  tutorials/epochs/plot_50_epochs_to_data_frame.py
Labels: ENH

#9015 MRG, ENH: viz.plot_drop_log() gains special-handling for subject=None
  doc/changes/latest.inc
  mne/epochs.py
  mne/report.py
  mne/viz/epochs.py
  tutorials/misc/plot_report.py
Labels: VIZ

#9175 BUG: Only use valid FIFF values for anonymization
  doc/changes/latest.inc
  mne/io/meas_info.py
  mne/io/tests/test_meas_info.py
Labels: FIX

#9179 FIX: Brain locale
  mne/viz/backends/_qt.py
Labels: FIX

#9136 MRG: Add `units` parameter to get_data for Raw
  doc/changes/latest.inc
  mne/defaults.py
  mne/io/base.py
  mne/io/tests/test_raw.py
  mne/tests/test_defaults.py
Labels: ENH, MEDIUM
