Repository mne-tools/mne-python, pull requests merged in 2021-09, with the labels that each got.

#9714 MRG: Refactor plot_alignment
  mne/viz/_3d.py
  mne/viz/_brain/_brain.py
  tutorials/forward/35_eeg_no_mri.py
Labels: VIZ

#9705 BUG: Fix tolerances
  mne/io/tests/test_raw.py
  mne/utils/tests/test_numerics.py
Labels: backport-candidate

#9758 Fix equalize event counts
  doc/changes/latest.inc
  mne/epochs.py
  mne/tests/test_epochs.py
Labels: BUG
