Repository mne-tools/mne-python, pull requests merged in 2021-12, with the labels that each got.

#10065 Don't warn when using decim with ICA.fit() on epochs
  mne/preprocessing/ica.py
  mne/preprocessing/tests/test_ica.py
Labels: backport-candidate

#10073 MRG: Fix permutation_cluster_1samp_test for 2D data when using TFCE
  doc/changes/latest.inc
  mne/stats/cluster_level.py
  mne/stats/tests/test_cluster_level.py
Labels: BUG

#10074 FIX: brain colormap lookup table
  doc/changes/latest.inc
  mne/viz/_brain/colormap.py
Labels: FIX, backport-candidate

#10082 MRG: Add scrollbar to report tag dropdown menu
  doc/changes/latest.inc
  mne/report/templates/header.html
Labels: backport-candidate

#10084 MRG: Make y a required parameter in CSP.fit_transform()
  mne/decoding/csp.py
  mne/decoding/mixin.py
Labels: backport-candidate

#9927 fix plot_compare_evokeds topo legend axes placement
  mne/viz/evoked.py
  mne/viz/topo.py
Labels: VIZ

#10087 fix trace offsets in butterfly mode
  doc/changes/latest.inc
  mne/viz/_mpl_figure.py
Labels: backport-candidate, VIZ

#10091 MRG: Use fixes._compare_version for version checks everywhere
  doc/conf.py
  mne/conftest.py
  mne/cov.py
  mne/datasets/_fetch.py
  mne/datasets/sleep_physionet/_utils.py
  mne/externals/tqdm/__init__.py
  mne/io/eeglab/tests/test_eeglab.py
  mne/surface.py
  mne/tests/test_epochs.py
  mne/time_frequency/tests/test_multitaper.py
  mne/utils/_testing.py
  mne/utils/tests/test_linalg.py
  mne/viz/_brain/_scraper.py
  mne/viz/backends/_notebook.py
  mne/viz/backends/_pyvista.py
  mne/viz/misc.py
  mne/viz/utils.py
  setup.cfg
Labels: code-health

#10067 [MRG] FIX: make all annotate_* funcs return annots with consistent orig_time
  doc/changes/latest.inc
  mne/io/nirx/tests/test_nirx.py
  mne/preprocessing/annotate_nan.py
  mne/preprocessing/artifact_detection.py
  mne/preprocessing/flat.py
  mne/preprocessing/tests/test_artifact_detection.py
  mne/preprocessing/tests/test_flat.py
Labels: backport-candidate

#10118 BUG: Time alignments between RAW and annotate_* funcs
  doc/changes/latest.inc
  mne/annotations.py
  mne/io/base.py
  mne/io/nirx/tests/test_nirx.py
  mne/preprocessing/annotate_nan.py
  mne/preprocessing/artifact_detection.py
  mne/preprocessing/flat.py
  mne/preprocessing/tests/test_annotate_nan.py
  mne/preprocessing/tests/test_artifact_detection.py
  mne/preprocessing/tests/test_flat.py
  mne/preprocessing/tests/test_maxwell.py
Labels: BUG, help-needed

#10134 newcontrib sphinx role [skip azp][skip github]
  doc/changes/latest.inc
  doc/conf.py
  doc/sphinxext/gh_substitutions.py
  doc/sphinxext/newcontrib_substitutions.py
Labels: DOC

#10136 MRG: Change intersphinx reference for MPL gridspec
  mne/viz/topomap.py
Labels: DOC

#9969 [ENH] Enable Epochs to store Annotations from Raw
  doc/changes/latest.inc
  mne/epochs.py
  mne/tests/test_epochs.py
Labels: ENH, API

#10153 Clarify supported software versions for NIRx reader
  mne/utils/docs.py
  tutorials/io/30_reading_fnirs_data.py
Labels: fNIRS
