Repository mne-tools/mne-python, pull requests merged in 2021-02, with the labels that each got.

#8874 Fix EEGLAB import
  doc/changes/latest.inc
  mne/datasets/utils.py
  mne/io/eeglab/eeglab.py
  mne/io/eeglab/tests/test_eeglab.py
Labels: ENH, backport-candidate

#8827 Ensure times at which chpi are fitted are valid samples
  mne/chpi.py
  mne/preprocessing/maxwell.py
  mne/tests/test_chpi.py
Labels: BUG

#8965 MRG: "GFP" trace in STC time viewer is actually RMS
  doc/changes/latest.inc
  mne/viz/_brain/_brain.py
  mne/viz/evoked.py
  tutorials/source-modeling/plot_mne_dspm_source_localization.py
Labels: VIZ, backport-candidate

#8963 Fix indexing dipoles read from a bdip file
  doc/changes/latest.inc
  mne/dipole.py
  mne/tests/test_dipole.py
Labels: BUG
