Repository mne-tools/mne-python, pull requests merged in 2021-11, with the labels that each got.

#9934 MRG: Improve random_state docstring & some other small doc fixes
  mne/preprocessing/ica.py
  mne/utils/docs.py
Labels: DOC

#9936 MRG: New attempt to slightly improve verbose docstring
  mne/decoding/receptive_field.py
  mne/inverse_sparse/mxne_optim.py
  mne/utils/docs.py
Labels: DOC

#9955 MAINT: Add config var for opt-in
  mne/utils/config.py
Labels: backport-candidate

#9956 MAINT: Bump mne-connectivity
  requirements_doc.txt
  tutorials/epochs/60_make_fixed_length_epochs.py
Labels: backport-candidate

#9963 fix missing connectivity image on homepage tile
  doc/_templates/homepage.html
Labels: backport-candidate

#9968 MRG, FIX: Fix interior check
  doc/changes/latest.inc
  mne/forward/_make_forward.py
  mne/forward/tests/test_make_forward.py
Labels: backport-candidate

#9972 MRG: Add "interaction" param to CoregistrationUI
  mne/gui/__init__.py
  mne/gui/_coreg.py
  mne/utils/docs.py
  mne/viz/_3d.py
Labels: ENH, FIX, API, VIZ

#9979 fix linkcheck
  doc/changes/0.18.inc
  doc/changes/names.inc
Labels: backport-candidate

#9973 import fix for scipy 1.8 pre
  mne/externals/pymatreader/pymatreader.py
  mne/externals/pymatreader/utils.py
  mne/io/eeglab/eeglab.py
  mne/minimum_norm/tests/test_inverse.py
  mne/viz/_3d.py
  mne/viz/topomap.py
  tools/github_actions_dependencies.sh
Labels: backport-candidate

#9988 MRG: Make check_version() use _compare_version() internally
  mne/utils/check.py
Labels: code-health

#9991 [BUG, MRG] Revisit affine registration
  doc/changes/latest.inc
  mne/tests/test_morph.py
  mne/tests/test_transforms.py
  mne/transforms.py
  tutorials/clinical/10_ieeg_localize.py
Labels: backport-candidate

#9998 MRG: Don't overwrite Report.fname upon saving
  doc/changes/latest.inc
  mne/report/report.py
Labels: backport-candidate

#9970 MRG: Add extensive checking for Report tags
  doc/changes/0.24.inc
  doc/changes/latest.inc
  mne/report/report.py
  mne/report/tests/test_report.py
  tutorials/intro/70_report.py
Labels: backport-candidate

#10004 Add argument overwrite to ICA.save()
  doc/changes/latest.inc
  mne/preprocessing/ica.py
  mne/preprocessing/tests/test_ica.py
Labels: backport-candidate

#10005 MRG, MAINT: Update for SciPy namespace
  mne/externals/pymatreader/pymatreader.py
  mne/externals/pymatreader/utils.py
  mne/io/eeglab/eeglab.py
  tools/github_actions_dependencies.sh
Labels: backport-candidate

#10002 Robust fif channel renaming of long channels names
  doc/changes/latest.inc
  mne/io/meas_info.py
  mne/io/tests/test_meas_info.py
Labels: backport-candidate

#10025 MRG, MAINT: Use better machine for CircleCI
  .circleci/config.yml
  tools/circleci_dependencies.sh
Labels: backport-candidate

#10036 Revert change to fNIRS tutorial
  tutorials/preprocessing/70_fnirs_processing.py
Labels: backport-candidate

#10041 decim is actually used for epochs
  mne/preprocessing/ica.py
Labels: backport-candidate

#10047 Add back pooch to sys_info; pin pooch min version
  doc/changes/latest.inc
  mne/utils/config.py
  requirements.txt
Labels: backport-candidate

#10058 Fix EDF channel type detection
  doc/changes/latest.inc
  mne/export/tests/test_export.py
  mne/io/edf/edf.py
  mne/io/edf/tests/test_edf.py
  mne/io/nihon/tests/test_nihon.py
Labels: backport-candidate
