Repository mne-tools/mne-python, pull requests merged in 2021-05, with the labels that each got.

#9365 better docs for permutation_cluster_test
  mne/stats/_adjacency.py
  mne/utils/docs.py
Labels: DOC

#8741 ENH: Add a playback button to the notebook 3d backend
  mne/viz/_brain/_brain.py
  mne/viz/_brain/tests/test_notebook.py
  mne/viz/backends/_abstract.py
  mne/viz/backends/_notebook.py
  mne/viz/backends/_qt.py
Labels: ENH

#9411 fix homepage link
  doc/conf.py
Labels: backport-candidate

#9426 FIX: brain save_movie
  mne/viz/_brain/_brain.py
  mne/viz/_brain/tests/test_brain.py
Labels: FIX
