Repository mne-tools/mne-python, pull requests merged in 2021-01, with the labels that each got.

#8503 MRG: Prototype of notebook viz (ipyvtk)
  doc/changes/latest.inc
  mne/viz/_brain/_brain.py
  mne/viz/_brain/_notebook.py
  mne/viz/_brain/mplcanvas.py
  mne/viz/_brain/tests/test.ipynb
  mne/viz/backends/_notebook.py
  server_environment.yml
Labels: VIZ

#8744 MRG: Support for non-FIFF files in Report.parse_folder
  doc/changes/latest.inc
  mne/report.py
  mne/tests/test_report.py
  server_environment.yml
Labels: ENH

#8708 MRG, ENH: Add a screenshot button to the notebook 3d backend
  mne/datasets/utils.py
  mne/label.py
  mne/viz/__init__.py
  mne/viz/_brain/_brain.py
  mne/viz/_brain/tests/test.ipynb
  mne/viz/_brain/tests/test_brain.py
  mne/viz/_brain/tests/test_notebook.py
  mne/viz/backends/_notebook.py
  mne/viz/backends/_pyvista.py
  mne/viz/utils.py
Labels: ENH

#8771 MRG: Brain silhouette
  doc/changes/latest.inc
  examples/inverse/plot_mixed_source_space_inverse.py
  mne/source_estimate.py
  mne/utils/docs.py
  mne/viz/_3d.py
  mne/viz/_brain/_brain.py
  mne/viz/_brain/tests/test_brain.py
  mne/viz/backends/_pyvista.py
  tutorials/source-modeling/plot_beamformer_lcmv.py
  tutorials/source-modeling/plot_visualize_stc.py
Labels: VIZ

#8775 MRG, BUG, DOC: derive GFP from average reference for EEG
  doc/changes/latest.inc
  doc/references.bib
  mne/viz/evoked.py
  mne/viz/tests/test_evoked.py
  tutorials/evoked/plot_20_visualize_evoked.py
  tutorials/evoked/plot_eeg_erp.py
Labels: BUG, VIZ, backport-candidate

#8730 MRG: support plot_stc in report
  doc/changes/latest.inc
  mne/report.py
  mne/viz/_brain/tests/test_brain.py
  tutorials/misc/plot_report.py
Labels: ENH

#8780 MRG, BUG: fix IO or read_ica_eeglab
  doc/changes/latest.inc
  mne/io/eeglab/eeglab.py
  mne/preprocessing/ica.py
  mne/preprocessing/tests/test_ica.py
  mne/utils/__init__.py
Labels: BUG

#8811 FIX missing Axes3D import in viz._3d._plot_mpl_stc
  doc/changes/latest.inc
  mne/viz/_3d.py
Labels: backport-candidate
