Repository mne-tools/mne-python, pull requests merged in 2022-08, with the labels that each got.

#11006 Use `scipy.io.loadmat()` fallback for EEGLAB reader
  doc/changes/latest.inc
  mne/io/eeglab/_eeglab.py
  mne/io/eeglab/eeglab.py
  mne/io/eeglab/tests/test_eeglab.py
  mne/utils/__init__.py
  mne/utils/check.py
Labels: backport-candidate

#11035 fix remaining resp: respiration!=response
  doc/_includes/channel_types.rst
  doc/changes/0.23.inc
Labels: backport-candidate

#11074 BUG: don't assume that channel info contains particular keys
  doc/changes/latest.inc
  doc/changes/names.inc
  mne/io/eeglab/eeglab.py
  mne/io/eeglab/tests/test_eeglab.py
Labels: backport-candidate

#11080 Add error message when conversion of EEG locs to head space fails
  doc/changes/latest.inc
  mne/channels/montage.py
  mne/channels/tests/test_montage.py
  mne/io/_digitization.py
Labels: BUG

#10184 add spectrum class
  doc/_static/style.css
  doc/changes/latest.inc
  doc/conf.py
  doc/references.bib
  doc/time_frequency.rst
  mne/channels/channels.py
  mne/cov.py
  mne/decoding/transformer.py
  mne/epochs.py
  mne/evoked.py
  mne/filter.py
  mne/html_templates/repr/spectrum.html.jinja
  mne/io/base.py
  mne/preprocessing/ica.py
  mne/simulation/tests/test_raw.py
  mne/time_frequency/__init__.py
  mne/time_frequency/multitaper.py
  mne/time_frequency/psd.py
  mne/time_frequency/spectrum.py
  mne/time_frequency/tests/test_csd.py
  mne/time_frequency/tests/test_multitaper.py
  mne/time_frequency/tests/test_psd.py
  mne/time_frequency/tests/test_spectrum.py
  mne/utils/check.py
  mne/utils/dataframe.py
  mne/utils/docs.py
  mne/utils/mixin.py
  mne/utils/numerics.py
  mne/viz/epochs.py
  mne/viz/ica.py
  mne/viz/raw.py
  mne/viz/tests/test_epochs.py
  mne/viz/tests/test_raw.py
  mne/viz/topomap.py
  mne/viz/utils.py
  setup.cfg
  tutorials/clinical/60_sleep.py
  tutorials/epochs/20_visualize_epochs.py
  tutorials/raw/40_visualize_raw.py
  tutorials/time-freq/10_spectrum_class.py
Labels: EOSS4

#11121 Mark legacy
  mne/time_frequency/spectrum.py
  mne/utils/docs.py
  mne/viz/epochs.py
  mne/viz/raw.py
  mne/viz/topomap.py
  mne/viz/utils.py
Labels: EOSS4
