Repository mne-tools/mne-python, pull requests merged in 2022-11, with the labels that each got.

#11303 BUG: Fix bug with unscale=True
  doc/changes/latest.inc
  mne/_freesurfer.py
  mne/tests/test_coreg.py
Labels: backport-candidate

#11301 Adapt institutional partners
  doc/_includes/institutional-partners.rst
  doc/_static/institution_logos/Donders.png
  doc/changes/names.inc
  doc/conf.py
Labels: website

#11318 BUG: Fix bug with report replacement
  doc/changes/latest.inc
  mne/report/report.py
  mne/report/tests/test_report.py
Labels: backport-candidate

#11328 fix fontawesome icon display
  doc/_templates/sidebar-quicklinks.html
  doc/conf.py
  doc/install/contributing.rst
  doc/install/index.rst
  doc/install/installers.rst
Labels: backport-candidate

#11335 Fix docstring list syntax
  mne/evoked.py
  mne/io/array/array.py
  mne/io/meas_info.py
Labels: DOC
