Repository mne-tools/mne-python, pull requests merged in 2022-04, with the labels that each got.

#10463 MRG: Fix command for headless installation
  doc/install/advanced.rst
Labels: backport-candidate

#10485 BUG: Fix add_figure for MNEQtBrowser
  doc/changes/latest.inc
  doc/conf.py
  mne/report/report.py
  mne/report/tests/test_report.py
  mne/utils/_bunch.py
  mne/utils/docs.py
  mne/viz/_scraper.py
  mne/viz/backends/_pyvista.py
  mne/viz/backends/renderer.py
  mne/viz/epochs.py
  mne/viz/ica.py
  mne/viz/raw.py
  mne/viz/utils.py
  tutorials/intro/70_report.py
Labels: backport-candidate

#10488 BUG: Fix URL
  doc/changes/names.inc
  mne/datasets/config.py
  tutorials/clinical/30_ecog.py
Labels: backport-candidate

#10457 Fix error in filtering documentation
  mne/viz/misc.py
  tutorials/preprocessing/25_background_filtering.py
Labels: DOC

#10498 Improve visualize evoked tutorial
  tutorials/evoked/20_visualize_evoked.py
Labels: DOC

#10502 MAINT: Standardize tests
  azure-pipelines.yml
  mne/beamformer/tests/test_lcmv.py
  mne/channels/tests/test_channels.py
  mne/channels/tests/test_interpolation.py
  mne/commands/tests/test_commands.py
  mne/conftest.py
  mne/datasets/misc/__init__.py
  mne/datasets/misc/_misc.py
  mne/export/tests/test_export.py
  mne/gui/__init__.py
  mne/gui/tests/test_coreg_gui.py
  mne/io/ctf/tests/test_ctf.py
  mne/io/eeglab/tests/test_eeglab.py
  mne/io/egi/tests/test_egi.py
  mne/io/eximia/tests/test_eximia.py
  mne/io/fieldtrip/tests/helpers.py
  mne/io/fieldtrip/tests/test_fieldtrip.py
  mne/io/nihon/tests/test_nihon.py
  mne/io/persyst/tests/test_persyst.py
  mne/preprocessing/nirs/tests/test_beer_lambert_law.py
  mne/preprocessing/tests/test_eeglab_infomax.py
  mne/preprocessing/tests/test_maxwell.py
  mne/tests/test_coreg.py
  mne/viz/_brain/tests/test_notebook.py
  mne/viz/backends/tests/test_renderer.py
  mne/viz/conftest.py
  mne/viz/tests/test_epochs.py
  mne/viz/tests/test_evoked.py
  mne/viz/tests/test_ica.py
  mne/viz/tests/test_raw.py
  tools/github_actions_download.sh
Labels: backport-candidate

#10500 BUG: Fix bug with themes on macOS
  doc/changes/latest.inc
  mne/icons/toolbar_move_horizontal@2x.png
  mne/icons/toolbar_move_vertical@2x.png
  mne/icons/toolbar_separator_horizontal.png
  mne/icons/toolbar_separator_horizontal@2x.png
  mne/icons/toolbar_separator_vertical@2x.png
  mne/viz/_scraper.py
  mne/viz/backends/_utils.py
  mne/viz/backends/tests/test_utils.py
Labels: backport-candidate

#10531 WIP: Copy BEM surfaces by default (don't symlink)
  doc/changes/latest.inc
  mne/bem.py
Labels: API, backport-candidate

#10548 MRG: Correct documented default number of CV splits in cross_val_multiscore()
  mne/decoding/base.py
Labels: DOC, backport-candidate

#10464 Allow making inverse solutions from fixed-orientation discrete forward models, enabling multi-dipole modeling
  examples/inverse/multi_dipole_model.py
  mne/forward/_make_forward.py
  mne/forward/forward.py
  mne/forward/tests/test_make_forward.py
  mne/inverse_sparse/tests/test_gamma_map.py
  mne/inverse_sparse/tests/test_mxne_inverse.py
  mne/minimum_norm/inverse.py
  mne/minimum_norm/tests/test_inverse.py
  mne/utils/docs.py
Labels: ENH

#10552 Use liblinear solver instead of lbgfs in all decoding examples
  examples/decoding/decoding_time_generalization_conditions.py
  examples/decoding/linear_model_patterns.py
  tutorials/machine-learning/50_decoding.py
Labels: DOC, backport-candidate

#10543 MRG: Fix coreg UI didn't start if only a high-resolution head model was available
  doc/changes/latest.inc
  mne/conftest.py
  mne/coreg.py
  mne/gui/_coreg.py
  mne/gui/tests/test_coreg_gui.py
  mne/tests/test_coreg.py
Labels: backport-candidate

#10515 Add support for BrainVision ahdr/amrk format, as produced by the V-AMP
  doc/changes/latest.inc
  mne/annotations.py
  mne/datasets/config.py
  mne/io/_read_raw.py
  mne/io/brainvision/brainvision.py
  mne/io/brainvision/tests/test_brainvision.py
Labels: ENH
