Repository mne-tools/mne-python, pull requests merged in 2022-06, with the labels that each got.

#10694 MRG: In Report, allow to add multiple figure or image elements to the same content block ("section")
  doc/changes/latest.inc
  mne/html_templates/report/bem.html.jinja
  mne/html_templates/report/code.html.jinja
  mne/html_templates/report/epochs.html.jinja
  mne/html_templates/report/evoked.html.jinja
  mne/html_templates/report/forward.html.jinja
  mne/html_templates/report/ica.html.jinja
  mne/html_templates/report/image.html.jinja
  mne/html_templates/report/inverse.html.jinja
  mne/html_templates/report/raw.html.jinja
  mne/html_templates/report/section.html.jinja
  mne/html_templates/report/toc.html.jinja
  mne/report/report.py
  mne/report/tests/test_report.py
  mne/utils/docs.py
  tutorials/intro/70_report.py
Labels: ENH, code-health

#10722 ENH: Add plot_projs_joint
  .gitignore
  doc/changes/latest.inc
  doc/visualization.rst
  mne/io/pick.py
  mne/utils/docs.py
  mne/viz/__init__.py
  mne/viz/_proj.py
  mne/viz/evoked.py
  mne/viz/tests/test_proj.py
  mne/viz/topomap.py
  mne/viz/utils.py
  tutorials/preprocessing/50_artifact_correction_ssp.py
Labels: EOSS4

#10727 MRG: Remove tutorial thumbnail popovers
  doc/_static/style.css
Labels: DOC, backport-candidate, a11y

#10733 MRG: Add verbose decorator to cross_val_multiscore()
  mne/decoding/base.py
Labels: code-health

#10763 BUG: Fixes for ARM architecture
  mne/bem.py
  mne/gui/tests/test_gui_api.py
  mne/inverse_sparse/mxne_optim.py
  mne/io/eeglab/tests/test_eeglab.py
  mne/preprocessing/tests/test_maxwell.py
  mne/source_estimate.py
  mne/tests/test_source_estimate.py
  mne/viz/_brain/_brain.py
  mne/viz/backends/_qt.py
  mne/viz/backends/renderer.py
  mne/viz/backends/tests/test_utils.py
Labels: code-health
