Repository mne-tools/mne-python, pull requests merged in 2022-09, with the labels that each got.

#11129 MAINT: Pop instead of del
  mne/viz/backends/_pyvista.py
Labels: backport-candidate

#11139 On ICA._reset(), reset current_fit to "unfitted"
  mne/preprocessing/ica.py
  mne/preprocessing/tests/test_ica.py
Labels: code-health

#11123 Standardize topomap args
  doc/changes/latest.inc
  examples/decoding/ems_filtering.py
  examples/decoding/linear_model_patterns.py
  examples/decoding/receptive_field_mtrf.py
  examples/inverse/mne_cov_power.py
  examples/preprocessing/eeg_bridging.py
  examples/preprocessing/eeg_csd.py
  examples/preprocessing/movement_compensation.py
  examples/preprocessing/virtual_evoked.py
  examples/stats/sensor_permutation_test.py
  examples/time_frequency/source_power_spectrum_opm.py
  examples/time_frequency/time_frequency_erds.py
  examples/visualization/evoked_topomap.py
  mne/cov.py
  mne/evoked.py
  mne/io/proj.py
  mne/preprocessing/_regress.py
  mne/preprocessing/ica.py
  mne/report/report.py
  mne/time_frequency/spectrum.py
  mne/time_frequency/tfr.py
  mne/utils/docs.py
  mne/viz/_proj.py
  mne/viz/evoked.py
  mne/viz/tests/test_topomap.py
  mne/viz/topomap.py
  mne/viz/utils.py
  tutorials/epochs/15_baseline_regression.py
  tutorials/epochs/40_autogenerate_metadata.py
  tutorials/inverse/20_dipole_fit.py
  tutorials/inverse/30_mne_dspm_loreta.py
  tutorials/io/60_ctf_bst_auditory.py
  tutorials/preprocessing/35_artifact_correction_regression.py
  tutorials/preprocessing/70_fnirs_processing.py
  tutorials/stats-sensor-space/75_cluster_ftest_spatiotemporal.py
  tutorials/time-freq/20_sensors_time_frequency.py
  tutorials/time-freq/50_ssvep.py
Labels: EOSS4
