Repository mne-tools/mne-python, pull requests merged in 2022-05, with the labels that each got.

#10580 MRG: Update installation instructions to ensure users end up with latest version of the conda-forge package
  doc/install/advanced.rst
  doc/install/manual_install.rst
Labels: DOC, backport-candidate

#10597 MRG: Recommend mamba instead of libmamba for installation
  doc/install/manual_install.rst
  doc/install/manual_install_platform_selector.html
Labels: backport-candidate

#10605 MAINT: Fix for pydata-sphinx-theme
  doc/_static/versions.json
  doc/conf.py
Labels: backport-candidate

#10619 Drop EEG rejection thresholds when replacing EEG with CSD channels
  doc/changes/latest.inc
  mne/preprocessing/_csd.py
  mne/preprocessing/tests/test_csd.py
Labels: backport-candidate

#10620 Simplify #10619
  mne/preprocessing/_csd.py
Labels: backport-candidate, code-health

#10622 MRG: Update installer links to point to 1.0.2_1
  doc/install/installers_platform_selector.html
Labels: backport-candidate

#10125 ENH: TDDR for Hb type fNIRS data
  doc/changes/latest.inc
  mne/preprocessing/nirs/_tddr.py
  mne/preprocessing/nirs/tests/test_temporal_derivative_distribution_repair.py
Labels: fNIRS

#10633 ENH: plot adjacency
  doc/changes/latest.inc
  doc/visualization.rst
  mne/channels/channels.py
  mne/viz/__init__.py
  mne/viz/tests/test_topomap.py
  mne/viz/topomap.py
  mne/viz/utils.py
  tutorials/stats-sensor-space/75_cluster_ftest_spatiotemporal.py
Labels: ENH

#10658 [MRG] DOC: clarify cluster-based permutation testing
  Makefile
  README.rst
  doc/changes/latest.inc
  doc/conf.py
  doc/install/contributing.rst
  doc/references.bib
  examples/decoding/ems_filtering.py
  examples/time_frequency/time_frequency_global_field_power.py
  mne/channels/channels.py
  mne/forward/forward.py
  mne/io/fiff/tests/test_raw_fiff.py
  mne/stats/_adjacency.py
  mne/stats/cluster_level.py
  mne/stats/parametric.py
  mne/surface.py
  mne/utils/docs.py
  tutorials/clinical/10_ieeg_localize.py
  tutorials/machine-learning/50_decoding.py
  tutorials/stats-sensor-space/10_background_stats.py
  tutorials/stats-sensor-space/40_cluster_1samp_time_freq.py
  tutorials/stats-sensor-space/75_cluster_ftest_spatiotemporal.py
  tutorials/stats-source-space/20_cluster_1samp_spatiotemporal.py
  tutorials/stats-source-space/30_cluster_ftest_spatiotemporal.py
  tutorials/stats-source-space/60_cluster_rmANOVA_spatiotemporal.py
  tutorials/stats-source-space/70_cluster_rmANOVA_time_freq.py
  tutorials/time-freq/50_ssvep.py
Labels: DOC

#10683 Don't special-case manual installation instructions for Apple Silicon anymore
  doc/install/manual_install.rst
  doc/install/manual_install_platform_selector.html
Labels: backport-candidate

#10685 MRG: Make read_evokeds() expand "~" to home directory
  doc/changes/latest.inc
  mne/evoked.py
Labels: backport-candidate

#10686 MRG: Fix sign checks in Evoked.get_peak()
  doc/changes/latest.inc
  mne/evoked.py
  mne/export/tests/test_export.py
  mne/io/egi/tests/test_egi.py
  mne/tests/test_evoked.py
  mne/tests/test_source_estimate.py
Labels: backport-candidate
