Repository mne-tools/mne-python, pull requests merged in 2022-01, with the labels that each got.

#10178 MRG: Add missing changelog entry for #10176
  doc/changes/latest.inc
Labels: DOC

#10203 FIX: helmet
  mne/gui/_coreg.py
  mne/viz/_3d.py
Labels: FIX

#10205 add function to reflow param entries
  mne/utils/docs.py
Labels: DOC

#10220 MRG: Use actual push button widgets for push buttons in Coreg UI
  doc/changes/latest.inc
  mne/gui/tests/test_gui_api.py
  mne/viz/_brain/_brain.py
  mne/viz/backends/_abstract.py
  mne/viz/backends/_notebook.py
  mne/viz/backends/_qt.py
Labels: a11y

#10239 MRG: Documentation improvements extracted from #10237
  doc/conf.py
  doc/mri.rst
  mne/channels/montage.py
  mne/coreg.py
  mne/gui/_coreg.py
  mne/io/_digitization.py
  mne/io/meas_info.py
  mne/utils/docs.py
Labels: DOC

#10241 MRG: In CoregistrationUI, use DigMontage for storing fiducials, factor out fiducials saving into new method, fix trans saving (extracted from #10237)
  mne/gui/_coreg.py
Labels: code-health

#10244 Allow QLabel widget text content to be selectable
  mne/gui/tests/test_gui_api.py
  mne/viz/backends/_abstract.py
  mne/viz/backends/_notebook.py
  mne/viz/backends/_qt.py
Labels: ENH, a11y

#10260 MRG: Refactor and extend a few things in CoregistrationUI
  mne/gui/_coreg.py
Labels: code-health

#10262 MRG: Lock CoregistrationUI widgets when placing fiducials
  mne/gui/_coreg.py
  mne/viz/backends/_qt.py
Labels: VIZ, a11y

#10265 MRG: read_trans() didn't expand ~ in path
  doc/changes/latest.inc
  mne/transforms.py
Labels: FIX
