Repository mne-tools/mne-python, pull requests merged in 2023-12, with the labels that each got.

#12264 BUG: Move defusedxml to optional dependencies
  doc/changes/devel.rst
  mne/channels/_dig_montage_utils.py
  mne/channels/_standard_montage_utils.py
  mne/channels/tests/test_montage.py
  mne/export/tests/test_export.py
  mne/io/egi/egimff.py
  mne/io/egi/events.py
  mne/io/egi/general.py
  mne/io/egi/tests/test_egi.py
  mne/io/nedf/nedf.py
  mne/io/nedf/tests/test_nedf.py
  pyproject.toml
Labels: backport-candidate

#12316 fix 404 link on devel landing page
  CONTRIBUTING.md
  doc/development/index.rst
Labels: DOC, backport-candidate

#12320 MAINT: Fix CIs
  mne/decoding/tests/test_transformer.py
  tools/github_actions_dependencies.sh
Labels: no-changelog-entry-needed
