Repository mne-tools/mne-python, pull requests merged in 2023-11, with the labels that each got.

#12211 Add tomli to rstcheck dependencies
  .pre-commit-config.yaml
Labels: BUG

#12236 Fix incorrect type hint in Neuralynx I/O module
  doc/api/reading_raw_data.rst
  doc/changes/devel.rst
  doc/changes/v1.6.rst
  doc/conf.py
  mne/io/neuralynx/neuralynx.py
Labels: backport-candidate

#12245 MRG: Remove `_version.py` file; and small doc cleanups
  .git_archival.txt
  .gitattributes
  Makefile
  doc/development/contributing.rst
  doc/install/manual_install.rst
  doc/install/updating.rst
  mne/__init__.py
  pyproject.toml
Labels: MAINT

#12248 BUG: Fix bug with last item access
  doc/changes/devel.rst
  mne/io/base.py
  mne/io/tests/test_raw.py
Labels: backport-candidate
