Repository mne-tools/mne-python, pull requests merged in 2024-03, with the labels that each got.

#12471 MAINT: Fix links
  doc/changes/names.inc
  doc/conf.py
Labels: no-changelog-entry-needed

#12477 Bump ruff to v0.3.0
  .pre-commit-config.yaml
  doc/conf.py
  doc/sphinxext/unit_role.py
  examples/datasets/hf_sef_data.py
  examples/decoding/decoding_csp_eeg.py
  examples/decoding/decoding_csp_timefreq.py
  examples/decoding/ssd_spatial_filters.py
  examples/io/elekta_epochs.py
  examples/preprocessing/css.py
  examples/preprocessing/eog_artifact_histogram.py
  examples/preprocessing/xdawn_denoising.py
  examples/visualization/eyetracking_plot_heatmap.py
  examples/visualization/topo_compare_conditions.py
  examples/visualization/topo_customized.py
  mne/_fiff/tests/test_meas_info.py
  mne/beamformer/resolution_matrix.py
  mne/beamformer/tests/test_lcmv.py
  mne/commands/mne_bti2fiff.py
  mne/commands/mne_clean_eog_ecg.py
  mne/commands/mne_make_scalp_surfaces.py
  mne/conftest.py
  mne/export/tests/test_export.py
  mne/forward/tests/test_forward.py
  mne/io/_read_raw.py
  mne/io/artemis123/tests/test_artemis123.py
  mne/io/besa/tests/test_besa.py
  mne/io/brainvision/tests/test_brainvision.py
  mne/io/edf/edf.py
  mne/io/eeglab/tests/test_eeglab.py
  mne/io/eyelink/_utils.py
  mne/io/eyelink/tests/test_eyelink.py
  mne/io/fiff/tests/test_raw_fiff.py
  mne/io/neuralynx/neuralynx.py
  mne/minimum_norm/resolution_matrix.py
  mne/minimum_norm/spatial_resolution.py
  mne/preprocessing/_lof.py
  mne/preprocessing/tests/test_ica.py
  mne/preprocessing/tests/test_ssp.py
  mne/report/js_and_css/bootstrap-icons/gen_css_for_mne.py
  mne/report/tests/test_report.py
  mne/source_space/tests/test_source_space.py
  mne/stats/tests/test_cluster_level.py
  mne/tests/test_bem.py
  mne/time_frequency/tfr.py
  mne/viz/circle.py
  mne/viz/evoked_field.py
  mne/viz/montage.py
  mne/viz/tests/test_3d.py
  mne/viz/tests/test_epochs.py
  mne/viz/tests/test_misc.py
  mne/viz/tests/test_raw.py
  mne/viz/ui_events.py
  tutorials/visualization/20_ui_events.py
Labels: dependencies, tests, no-changelog-entry-needed

#12478 MAINT: Fix pip-pre errors
  tools/azure_dependencies.sh
  tools/github_actions_dependencies.sh
Labels: no-changelog-entry-needed

#12482 MAINT: Include OpenMEEG in pre jobs
  mne/conftest.py
  tools/azure_dependencies.sh
  tools/github_actions_dependencies.sh
Labels: no-changelog-entry-needed

#12487 fixes found by sphinx-lint
  doc/_includes/channel_interpolation.rst
  doc/_includes/forward.rst
  doc/_includes/ssp.rst
  doc/api/events.rst
  doc/api/file_io.rst
  doc/changes/v0.10.rst
  doc/changes/v0.12.rst
  doc/changes/v0.13.rst
  doc/changes/v0.15.rst
  doc/changes/v0.17.rst
  doc/changes/v1.2.rst
  doc/documentation/datasets.rst
Labels: no-changelog-entry-needed

#12494 Do not set browse raw icon when app icon already exists
  mne/viz/backends/_utils.py
Labels: no-changelog-entry-needed

#12496 MAINT: Work around sklearn bug
  mne/preprocessing/tests/test_lof.py
Labels: no-changelog-entry-needed

#12499 Remove bundle name hack on macOS
  mne/viz/backends/_utils.py
Labels: no-changelog-entry-needed

#12506 MAINT: Reenable pre scipy and numpy
  azure-pipelines.yml
  tools/azure_dependencies.sh
  tools/github_actions_dependencies.sh
Labels: no-changelog-entry-needed

#12511 MAINT: Reenable NumPy 2.0
  mne/utils/config.py
  tools/azure_dependencies.sh
  tools/github_actions_dependencies.sh
Labels: no-changelog-entry-needed

#12514 don't rely on inst_type to triage class constructors
  mne/time_frequency/tests/test_tfr.py
  mne/time_frequency/tfr.py
Labels: EOSS4, no-changelog-entry-needed

#12520 MAINT: Restore OMP_NUM_THREADS=2 on Windows
  .github/workflows/tests.yml
  azure-pipelines.yml
  mne/export/_edf.py
  mne/export/tests/test_export.py
  mne/morph.py
  mne/utils/dataframe.py
  tools/azure_dependencies.sh
  tools/github_actions_dependencies.sh
  tools/install_pre_requirements.sh
Labels: no-changelog-entry-needed
