Repository mne-tools/mne-python, pull requests merged in 2024-11, with the labels that each got.

#12941 fix ref=canonical in HTML page headers
  doc/_templates/layout.html
Labels: no-changelog-entry-needed

#12947 DOC: Reflow IDE doc
  doc/_static/js/set_installer_tab.js
  doc/install/ides.rst
  doc/install/index.rst
  doc/install/installers.rst
  doc/install/manual_install.rst
Labels: no-changelog-entry-needed

#12948 doc: clarify bids split naming
  mne/utils/docs.py
Labels: no-changelog-entry-needed, skip-changelog-checks

#12957 fix typo: shrikage -> shrinkage
  mne/cov.py
Labels: no-changelog-entry-needed

#12951 MAINT: Fixes for latest sklearn
  mne/decoding/base.py
  mne/decoding/ems.py
  mne/decoding/receptive_field.py
  mne/decoding/search_light.py
  mne/decoding/ssd.py
  mne/decoding/tests/test_base.py
  mne/decoding/tests/test_receptive_field.py
  mne/decoding/tests/test_search_light.py
  mne/decoding/time_delaying_ridge.py
  mne/fixes.py
  mne/preprocessing/xdawn.py
  tools/install_pre_requirements.sh
Labels: no-changelog-entry-needed

#12960 Some additions to the dipole orientation tutorial.
  doc/changes/devel/12960.other.rst
  tutorials/inverse/35_dipole_orientations.py
Labels: DOC

#12967 BUG: Fix bug with anonymization
  mne/_fiff/meas_info.py
  mne/_fiff/proc_history.py
  mne/_fiff/tests/test_meas_info.py
  mne/_fiff/write.py
  mne/io/fiff/tests/test_raw_fiff.py
  mne/io/tests/test_raw.py
  mne/utils/_testing.py
  mne/utils/numerics.py
Labels: no-changelog-entry-needed

#12973 DOC: fix note in legacy pick_channels func
  mne/channels/channels.py
Labels: no-changelog-entry-needed, skip-changelog-checks

#12972 DOC: specify tmax_raw param may be None, and what it means
  mne/utils/docs.py
Labels: no-changelog-entry-needed, skip-changelog-checks

#12976 DOC: add meegkit to related software suite
  doc/sphinxext/related_software.py
  tools/circleci_dependencies.sh
Labels: no-changelog-entry-needed, skip-changelog-checks

#12983 DOC: fix numpy docstr example Vectorizer()
  mne/decoding/transformer.py
Labels: no-changelog-entry-needed, skip-changelog-checks

#12984 do not log about using set_montage AGAIN if it has never been used
  mne/_fiff/reference.py
  mne/_fiff/tests/test_reference.py
Labels: no-changelog-entry-needed, skip-changelog-checks

#12991 MAINT: Unpin VTK
  .github/workflows/tests.yml
  azure-pipelines.yml
  tools/azure_dependencies.sh
  tools/install_pre_requirements.sh
Labels: no-changelog-entry-needed
