Repository mne-tools/mne-python, pull requests merged in 2024-10, with the labels that each got.

#12872 Update roadmap
  doc/development/roadmap.rst
Labels: no-changelog-entry-needed

#12883 make HTML repr for Forward match others
  mne/html_templates/repr/_channels.html.jinja
  mne/html_templates/repr/forward.html.jinja
  mne/html_templates/repr/static/_channels.html.jinja
  tutorials/forward/35_eeg_no_mri.py
Labels: no-changelog-entry-needed

#12886 Update spacing for comments in pyproject.toml
  pyproject.toml
Labels: no-changelog-entry-needed

#12891 Cast tuple of filenames to list to improve error handling
  mne/io/base.py
Labels: no-changelog-entry-needed

#12890 Sync README dependencies with pyproject.toml
  .pre-commit-config.yaml
  README.rst
  pyproject.toml
  tools/hooks/sync_dependencies.py
Labels: no-changelog-entry-needed

#12902 MAINT: Avoid problematic PySide6
  azure-pipelines.yml
  environment.yml
  pyproject.toml
Labels: no-changelog-entry-needed

#12915 Backport PR #12909 on branch maint/1.8 (Fix GDF NumPy >= 2)
  doc/changes/devel/12909.bugfix.rst
  mne/io/edf/edf.py
Labels: backport-candidate

#12914 Autogenerate environment.yml file from pyproject.toml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  environment.yml
  mne/utils/config.py
  pyproject.toml
  tools/azure_dependencies.sh
  tools/hooks/update_environment_file.py
Labels: MAINT, no-changelog-entry-needed

#12900 DOC: Document Linux desktop workaround
  doc/_static/default_linux_dock_icon.png
  doc/_static/mne_python_dock_icon.png
  doc/install/advanced.rst
Labels: no-changelog-entry-needed

#12928 MAINT: Fix tests
  .github/workflows/tests.yml
  doc/sphinxext/mne_doc_utils.py
  mne/conftest.py
  mne/decoding/receptive_field.py
  mne/decoding/tests/test_receptive_field.py
  mne/stats/regression.py
  mne/stats/tests/test_regression.py
Labels: no-changelog-entry-needed

#12898 Drop Mambaforge Python distribution, add warning regarding Anaconda
  doc/install/manual_install_python.rst
  doc/links.inc
Labels: DOC, no-changelog-entry-needed

#12932 Add mne-lsl to config wildcards
  mne/utils/config.py
Labels: no-changelog-entry-needed

#12933 Fix unit handling for µV and parsing of birthday in ANT format
  mne/io/ant/ant.py
Labels: no-changelog-entry-needed
