Repository mne-tools/mne-python, pull requests merged in 2024-06, with the labels that each got.

#12637 Add docstring details in epoch readers
  mne/io/eeglab/eeglab.py
  mne/io/kit/kit.py
Labels: DOC, no-changelog-entry-needed

#12645 MAINT: Switch to scientific python v1
  .github/workflows/check_changelog.yml
  mne/_fiff/tag.py
  mne/io/fiff/tests/test_raw_fiff.py
  tools/install_pre_requirements.sh
Labels: no-changelog-entry-needed

#12647 MAINT: Update action [skip azp]
  .github/workflows/circle_artifacts.yml
Labels: no-changelog-entry-needed

#12651 FIX: Fix combine check
  mne/beamformer/tests/test_lcmv.py
  mne/stats/_adjacency.py
  mne/stats/tests/test_cluster_level.py
  mne/utils/check.py
  tutorials/stats-sensor-space/40_cluster_1samp_time_freq.py
  tutorials/stats-sensor-space/75_cluster_ftest_spatiotemporal.py
Labels: no-changelog-entry-needed

#12661 Fix EDF/BDF filter warning bug
  doc/changes/devel/12661.bugfix.rst
  mne/io/edf/edf.py
  mne/io/edf/tests/test_edf.py
Labels: backport-candidate

#12666 Backport PR #12661 on branch maint/1.7 (Fix EDF/BDF filter warning bug)
  .github/workflows/release.yml
  CITATION.cff
  azure-pipelines.yml
  codemeta.json
  doc/changes/devel/12633.bugfix.rst
  doc/changes/v1.7.rst
  mne/conftest.py
  mne/io/edf/edf.py
  mne/io/edf/tests/test_edf.py
  mne/io/fiff/tests/test_raw_fiff.py
  pyproject.toml
  tools/generate_codemeta.py
Labels: backport-candidate, skip-changelog-checks

#12667 MAINT: Tweak which branches actions run on
  .github/workflows/check_changelog.yml
  .github/workflows/release.yml
Labels: no-changelog-entry-needed

#12668 MAINT: Update installer versions
  CITATION.cff
  codemeta.json
  doc/changes/v1.7.rst
  doc/install/installers.rst
Labels: backport-candidate, no-changelog-entry-needed

#12671 Backport PR #12668 on branch maint/1.7 (MAINT: Update installer versions)
  doc/install/installers.rst
Labels: backport-candidate, no-changelog-entry-needed

#12673 NumPy 2.0 compat problems in doc build
  doc/sphinxext/mne_doc_utils.py
  tools/circleci_dependencies.sh
Labels: backport-candidate, no-changelog-entry-needed

#12675 Add release.yaml to ignore bot authors
  .github/release.yaml
Labels: no-changelog-entry-needed

#12635 Backport PR #12616 on branch maint/1.7 (Fix `EpochsTFR.add_channels()`)
  doc/changes/devel/12616.bugfix.rst
  mne/channels/channels.py
  mne/time_frequency/tests/test_tfr.py
Labels: BUG, backport-candidate

#12677 MAINT: Fix doc build
  .circleci/config.yml
  .github/dependabot.yml
  .github/workflows/tests.yml
  environment.yml
  tools/circleci_dependencies.sh
  tools/github_actions_env_vars.sh
  tools/install_pre_requirements.sh
  tutorials/inverse/50_beamformer_lcmv.py
Labels: backport-candidate, no-changelog-entry-needed

#12678 Ensure we're testing macOS on Intel machines, too
  .github/workflows/tests.yml
Labels: backport-candidate, tests, no-changelog-entry-needed

#12680 Backport PR #12678 on branch maint/1.7 (Ensure we're testing macOS on Intel machines, too)
  .github/workflows/tests.yml
Labels: backport-candidate, tests, no-changelog-entry-needed

#12689 MAINT: Restore SciPy pre
  tools/install_pre_requirements.sh
Labels: no-changelog-entry-needed

#12691 Correct `Epochs.apply_function` docstring
  mne/utils/docs.py
Labels: DOC, no-changelog-entry-needed
