Repository mne-tools/mne-python, pull requests merged in 2024-05, with the labels that each got.

#12592 MAINT: Fix faulty links
  .github/workflows/autofix.yml
  doc/conf.py
  examples/preprocessing/eeg_bridging.py
  mne/preprocessing/_csd.py
Labels: no-changelog-entry-needed

#12593 BUG: Fix epochs interpolation for sEEG and don't interpolate over spans in electrodes and don't include stray contacts from other electrodes circumstantially in a line with an electrode
  doc/changes/devel/12593.bugfix.rst
  mne/channels/interpolation.py
  mne/channels/tests/test_interpolation.py
Labels: BUG, backport-candidate

#12598 Fix docstring of argument 'phase' in construct_iir_filter
  mne/filter.py
  mne/time_frequency/spectrum.py
  mne/time_frequency/tfr.py
Labels: no-changelog-entry-needed

#12595 Website homepage tweaks (funder logo, avatar size)
  doc/_static/funding/cds-dark.svg
  doc/_static/funding/cds.png
  doc/_static/funding/cds.svg
  doc/_static/style.css
  doc/conf.py
  doc/funding.rst
  pyproject.toml
Labels: no-changelog-entry-needed

#12601 MAINT: Use intersphinx_registry
  doc/conf.py
  mne/viz/_brain/_brain.py
  pyproject.toml
Labels: no-changelog-entry-needed

#12610 FIX: Fixes for pip-pre
  .git-blame-ignore-revs
  examples/decoding/decoding_rsa_sgskip.py
  examples/decoding/decoding_xdawn_eeg.py
  mne/decoding/tests/test_base.py
  mne/decoding/tests/test_search_light.py
  mne/stats/_adjacency.py
  mne/viz/backends/_pyvista.py
  tools/install_pre_requirements.sh
Labels: no-changelog-entry-needed

#12570 MAINT: Cleaner 3D vol viewer code
  mne/viz/_3d.py
  mne/viz/tests/test_3d_mpl.py
  tutorials/clinical/20_seeg.py
  tutorials/inverse/50_beamformer_lcmv.py
Labels: no-changelog-entry-needed

#12617 Clean-up __contains__ code and add comment for Info
  mne/_fiff/meas_info.py
Labels: no-changelog-entry-needed

#12619 Brain sliders hotfix
  examples/inverse/source_space_snr.py
  mne/viz/_brain/_brain.py
Labels: no-changelog-entry-needed

#12616 Fix `EpochsTFR.add_channels()`
  doc/changes/devel/12616.bugfix.rst
  mne/channels/channels.py
  mne/time_frequency/tests/test_tfr.py
Labels: BUG, backport-candidate

#12622 DOC: blink interpolation changes annot descs
  mne/preprocessing/eyetracking/_pupillometry.py
Labels: no-changelog-entry-needed

#12625 Fix intersphinx_registry API break
  doc/conf.py
  pyproject.toml
Labels: no-changelog-entry-needed

#12631 MAINT: More lenient timeout for downloader
  mne/datasets/utils.py
Labels: no-changelog-entry-needed

#12633 [BUG] Cross-spectral density missing frequencies
  doc/changes/devel/12633.bugfix.rst
  mne/time_frequency/csd.py
  mne/time_frequency/tests/test_csd.py
Labels: on-merge: backport to maint/1.7
