Repository mne-tools/mne-python, pull requests merged in 2024-07, with the labels that each got.

#12706 MAINT: Fix doc build
  tools/circleci_dependencies.sh
  tutorials/preprocessing/70_fnirs_processing.py
Labels: no-changelog-entry-needed

#12692 MAINT: Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no-changelog-entry-needed

#12708 ENH: Parallel example execution in doc build
  .circleci/config.yml
  doc/conf.py
  doc/sphinxext/mne_doc_utils.py
  mne/report/report.py
  mne/report/tests/test_report.py
  tools/circleci_bash_env.sh
  tools/circleci_download.sh
Labels: no-changelog-entry-needed

#12713 Update license year to 2024
  LICENSE.txt
Labels: no-changelog-entry-needed, skip-changelog-checks

#12712 Add license header to mne.stats.erp
  mne/stats/erp.py
Labels: no-changelog-entry-needed, skip-changelog-checks

#12703 Scale points and labels in montage plot
  doc/changes/devel/12703.newfeature.rst
  mne/channels/montage.py
  mne/viz/montage.py
Labels: VIZ

#12688 Disable the "Back to top" button in the documentation
  doc/changes/devel/12688.other.rst
  doc/conf.py
Labels: DOC

#12722 DOC: do not use sphinx gallery comment as section header
  examples/visualization/evoked_topomap.py
  tutorials/machine-learning/50_decoding.py
Labels: no-changelog-entry-needed, skip-changelog-checks

#12726 DOC: Document CSS more completely
  mne/preprocessing/_css.py
  mne/preprocessing/tests/test_css.py
Labels: no-changelog-entry-needed

#12729 pin h5io to >= 0.2.4
  pyproject.toml
Labels: no-changelog-entry-needed

#12732 BUG: Fix bug with SNIRF date
  mne/io/snirf/_snirf.py
  mne/io/snirf/tests/test_snirf.py
Labels: no-changelog-entry-needed

#12737 Add `_typing.py` module (follow-up to #12733)
  mne/utils/_typing.py
  mne/utils/mixin.py
Labels: no-changelog-entry-needed

#12736 Add a type guard to the metadata tutorial
  tutorials/epochs/30_epochs_metadata.py
Labels: DOC, no-changelog-entry-needed

#12738 Remove need for `Union` and `Optional` type annotations in Python 3.9
  mne/channels/channels.py
  mne/evoked.py
  mne/html_templates/_templates.py
  mne/preprocessing/ica.py
  mne/report/report.py
  mne/viz/_3d.py
  mne/viz/ui_events.py
Labels: no-changelog-entry-needed

#12716 DOC: Update install docs for Spyder
  doc/install/installers.rst
  doc/install/manual_install.rst
  mne/preprocessing/ecg.py
  mne/preprocessing/tests/test_ecg.py
  mne/rank.py
  pyproject.toml
Labels: no-changelog-entry-needed

#12741 Fix documentation of birthday field in Info
  mne/_fiff/meas_info.py
Labels: DOC, no-changelog-entry-needed

#12744 channel_types: add important note on eye-tracking
  mne/_fiff/meas_info.py
Labels: no-changelog-entry-needed, skip-changelog-checks

#12751 BUG: Fix bug with f-string
  mne/rank.py
  mne/tests/test_rank.py
Labels: no-changelog-entry-needed

#12757 3 miscellaneous documentation fixes
  README.rst
  doc/install/advanced.rst
  doc/install/check_installation.rst
  mne/preprocessing/eyetracking/_pupillometry.py
Labels: no-changelog-entry-needed, skip-changelog-checks
