Repository mne-tools/mne-python, pull requests merged in 2024-09, with the labels that each got.

#12823 MAINT: Fix for dipy deprecation
  .git-blame-ignore-revs
  examples/inverse/morph_volume_stc.py
  mne/morph.py
  mne/preprocessing/ieeg/_volume.py
  mne/tests/test_morph.py
  mne/transforms.py
Labels: no-changelog-entry-needed

#12826 Fix docstring typos
  mne/preprocessing/hfc.py
Labels: no-changelog-entry-needed

#12832 MAINT: No sklearn nightly for now
  tools/install_pre_requirements.sh
Labels: no-changelog-entry-needed

#12838 Disable unicode symbols in `mne.sys_info()` on Windows
  mne/utils/config.py
Labels: no-changelog-entry-needed

#12839 hotfix elc reader
  mne/channels/_standard_montage_utils.py
  mne/channels/montage.py
  mne/channels/tests/test_montage.py
  tutorials/inverse/70_eeg_mri_coords.py
Labels: no-changelog-entry-needed, skip-changelog-checks

#12841 [MRG] Add additional tests for ant reader
  doc/changes/devel/12792.newfeature.rst
  mne/datasets/config.py
  mne/io/ant/ant.py
  mne/io/ant/tests/test_ant.py
  pyproject.toml
  tools/vulture_allowlist.py
  tutorials/io/20_reading_eeg_data.py
Labels: skip-changelog-checks

#12850 FIX: use meters for pupil SI, not moles
  mne/defaults.py
Labels: no-changelog-entry-needed

#12845 DOC: Document installer uninstallation
  doc/Makefile
  doc/_static/js/set_installer_tab.js
  doc/_static/js/update_installer_version.js
  doc/install/installers.rst
Labels: no-changelog-entry-needed

#12861 DOC: impedances may be obtained for BrainVision
  mne/io/brainvision/brainvision.py
Labels: no-changelog-entry-needed, skip-changelog-checks

#12865 [MAINT] Update minimum Python version to 3.10 in `environment.yml`
  environment.yml
Labels: no-changelog-entry-needed

#12860 DOC: ICA -> fix typo, add func ref, use list
  mne/decoding/tests/test_base.py
  mne/preprocessing/ica.py
  mne/utils/progressbar.py
Labels: no-changelog-entry-needed, skip-changelog-checks

#12867 FIX: limit ncols to a reasonable max in plot_events
  mne/viz/misc.py
Labels: no-changelog-entry-needed, skip-changelog-checks

#12788 fix HTML repr table rendering
  doc/_static/style.css
  mne/html_templates/repr/_acquisition.html.jinja
  mne/html_templates/repr/_channels.html.jinja
  mne/html_templates/repr/_filters.html.jinja
  mne/html_templates/repr/_general.html.jinja
  mne/html_templates/repr/epochs.html.jinja
  mne/html_templates/repr/evoked.html.jinja
  mne/html_templates/repr/forward.html.jinja
  mne/html_templates/repr/ica.html.jinja
  mne/html_templates/repr/info.html.jinja
  mne/html_templates/repr/inverse_operator.html.jinja
  mne/html_templates/repr/raw.html.jinja
  mne/html_templates/repr/spectrum.html.jinja
  mne/html_templates/repr/static/_section_header_row.html.jinja
  mne/html_templates/repr/static/repr.css
  mne/html_templates/repr/static/repr.js
  mne/html_templates/repr/tfr.html.jinja
  tutorials/intro/70_report.py
  tutorials/io/70_reading_eyetracking_data.py
  tutorials/raw/20_event_arrays.py
Labels: no-changelog-entry-needed

#12866 DOC: clean up ECG ICA docstrs
  mne/preprocessing/ecg.py
  mne/preprocessing/ica.py
Labels: no-changelog-entry-needed, skip-changelog-checks

#12868 [MRG] Remove impedances in ant reader in favor of an example using antio
  examples/io/read_impedances.py
  mne/decoding/tests/test_receptive_field.py
  mne/io/ant/ant.py
  mne/io/ant/tests/test_ant.py
  pyproject.toml
Labels: no-changelog-entry-needed

#12870 Add toml-sort to sort pyproject.toml
  .pre-commit-config.yaml
  pyproject.toml
Labels: no-changelog-entry-needed

#12878 BUG: Fix bug with Path casting
  mne/io/fiff/raw.py
  mne/io/fiff/tests/test_raw_fiff.py
Labels: no-changelog-entry-needed
