Repository mne-tools/mne-python, pull requests merged in 2024-08, with the labels that each got.

#12765 MAINT: Sort `names.inc` using pre-commit hook
  .circleci/config.yml
  .pre-commit-config.yaml
  doc/Makefile
  doc/changes/names.inc
  doc/changes/v1.7.rst
  doc/conf.py
  doc/sphinxext/related_software.py
  mne/io/neuralynx/neuralynx.py
  mne/io/neuralynx/tests/test_neuralynx.py
  pyproject.toml
Labels: no-changelog-entry-needed

#12770 MAINT: Test against pymatreader dev version
  examples/inverse/morph_volume_stc.py
  tools/circleci_dependencies.sh
  tools/install_pre_requirements.sh
Labels: no-changelog-entry-needed

#12776 Website fixes
  doc/_static/style.css
  doc/_templates/copyright.html
  doc/_templates/sidebar-quicklinks.html
Labels: no-changelog-entry-needed

#12778 BUG: Fix bug with doc rebuilds being forced
  doc/sphinxext/contrib_avatars.py
  doc/sphinxext/gen_commands.py
  mne/utils/__init__.pyi
  mne/utils/numerics.py
  mne/utils/tests/test_numerics.py
Labels: no-changelog-entry-needed

#12786 BUG: Fix bug with example
  tutorials/stats-sensor-space/70_cluster_rmANOVA_time_freq.py
Labels: no-changelog-entry-needed

#12793 MAINT: Iterate faster on credit [ci skip]
  .github/workflows/credit.yml
Labels: no-changelog-entry-needed

#12799 MAINT: Apply UP038
  mne/_fiff/meas_info.py
  mne/_fiff/open.py
  mne/_fiff/pick.py
  mne/_fiff/proj.py
  mne/_fiff/reference.py
  mne/_fiff/write.py
  mne/_ola.py
  mne/annotations.py
  mne/bem.py
  mne/channels/channels.py
  mne/channels/layout.py
  mne/cov.py
  mne/decoding/base.py
  mne/decoding/ssd.py
  mne/decoding/transformer.py
  mne/epochs.py
  mne/event.py
  mne/evoked.py
  mne/filter.py
  mne/forward/forward.py
  mne/gui/_coreg.py
  mne/inverse_sparse/mxne_inverse.py
  mne/io/base.py
  mne/io/edf/edf.py
  mne/io/eeglab/eeglab.py
  mne/io/fil/fil.py
  mne/io/hitachi/hitachi.py
  mne/io/kit/coreg.py
  mne/io/kit/kit.py
  mne/io/tests/test_raw.py
  mne/label.py
  mne/minimum_norm/inverse.py
  mne/minimum_norm/time_frequency.py
  mne/morph.py
  mne/preprocessing/artifact_detection.py
  mne/preprocessing/ica.py
  mne/preprocessing/maxwell.py
  mne/preprocessing/xdawn.py
  mne/rank.py
  mne/report/report.py
  mne/simulation/raw.py
  mne/source_estimate.py
  mne/stats/regression.py
  mne/tests/test_import_nesting.py
  mne/time_frequency/tfr.py
  mne/transforms.py
  mne/utils/_logging.py
  mne/utils/check.py
  mne/utils/misc.py
  mne/utils/mixin.py
  mne/utils/numerics.py
  mne/viz/_3d.py
  mne/viz/_brain/_brain.py
  mne/viz/backends/_qt.py
  mne/viz/evoked.py
  mne/viz/ica.py
  mne/viz/misc.py
  mne/viz/topomap.py
  mne/viz/utils.py
  pyproject.toml
Labels: no-changelog-entry-needed

#12800 Update hash and version of testing dataset
  mne/datasets/config.py
Labels: no-changelog-entry-needed

#12813 Add missing @testing.requires_testing_data
  mne/io/ant/tests/test_ant.py
Labels: no-changelog-entry-needed

#12812 DOC: read_annotations also reads BDF and GDF
  mne/annotations.py
Labels: no-changelog-entry-needed, skip-changelog-checks

#12820 MAINT: Fix bugs with code credit and linking
  .github/workflows/credit.yml
  .mailmap
  doc/changes/names.inc
  doc/changes/v0.10.rst
  doc/changes/v0.11.rst
  doc/changes/v0.12.rst
  doc/changes/v0.13.rst
  doc/changes/v0.14.rst
  doc/changes/v0.15.rst
  doc/changes/v0.16.rst
  doc/changes/v0.18.rst
  doc/changes/v0.20.rst
  doc/changes/v0.21.rst
  doc/changes/v0.22.rst
  doc/changes/v0.23.rst
  doc/changes/v0.24.rst
  doc/changes/v0.8.rst
  doc/changes/v0.9.rst
  doc/changes/v1.1.rst
  doc/changes/v1.7.rst
  doc/changes/v1.8.rst
  doc/conf.py
  doc/sphinxext/credit_tools.py
  doc/sphinxext/mne_doc_utils.py
  doc/sphinxext/related_software.py
  examples/decoding/decoding_csp_timefreq.py
  examples/decoding/decoding_rsa_sgskip.py
  examples/decoding/decoding_spatio_temporal_source.py
  examples/decoding/decoding_spoc_CMC.py
  examples/decoding/decoding_time_generalization_conditions.py
  examples/decoding/decoding_unsupervised_spatial_filter.py
  examples/decoding/ems_filtering.py
  examples/decoding/linear_model_patterns.py
  examples/io/read_neo_format.py
  mne/conftest.py
  pyproject.toml
Labels: no-changelog-entry-needed

#12815 [MRG] Fix missing safety around device_info field
  examples/io/read_neo_format.py
  mne/_fiff/meas_info.py
Labels: backport-candidate, no-changelog-entry-needed

#12810 [MRG] Improves functionality of ANT Neuro reader
  mne/datasets/config.py
  mne/io/ant/ant.py
  mne/io/ant/tests/test_ant.py
  tools/vulture_allowlist.py
Labels: no-changelog-entry-needed
