Repository mne-tools/mne-python, pull requests merged in 2025-07, with the labels that each got.

#13304 Update docstring to reflect default setting in annotations
  doc/conf.py
  doc/links.inc
  mne/annotations.py
  mne/utils/docs.py
Labels: no-changelog-entry-needed

#13308 BUG: Fixes for old sklearn
  environment.yml
  mne/decoding/_fixes.py
  mne/decoding/tests/test_base.py
  mne/decoding/tests/test_csp.py
  mne/decoding/tests/test_ems.py
  mne/decoding/tests/test_ssd.py
  mne/decoding/tests/test_time_frequency.py
  mne/decoding/tests/test_transformer.py
  mne/decoding/transformer.py
  mne/inverse_sparse/tests/test_mxne_inverse.py
  pyproject.toml
  tools/environment_old.yml
  tools/hooks/update_environment_file.py
Labels: no-changelog-entry-needed

#13313 ENH: Cleaner forward solution plotting options
  azure-pipelines.yml
  mne/_fiff/tests/test_constants.py
  mne/bem.py
  mne/conftest.py
  mne/datasets/tests/test_datasets.py
  mne/html_templates/report/forward.html.jinja
  mne/html_templates/report/image.html.jinja
  mne/preprocessing/tests/test_fine_cal.py
  mne/report/report.py
  mne/report/tests/test_report.py
  tutorials/intro/70_report.py
Labels: no-changelog-entry-needed

#13315 MAINT: Make MxNE test more robust
  mne/inverse_sparse/tests/test_mxne_inverse.py
Labels: no-changelog-entry-needed

#13331 Add icon links to our donation pages
  doc/_static/js/custom-icons.js
  doc/_static/style.css
  doc/conf.py
Labels: backport-candidate, no-changelog-entry-needed

#13336 MAINT: Fix ref cycle with vtkPolyData
  doc/sphinxext/mne_doc_utils.py
  mne/gui/_coreg.py
Labels: backport-candidate, no-changelog-entry-needed

#13337 Backport PR #13336 on branch maint/1.10 (MAINT: Fix ref cycle with vtkPolyData)
  doc/sphinxext/mne_doc_utils.py
  mne/gui/_coreg.py
Labels: backport-candidate, no-changelog-entry-needed

#13344 Backport PR #13341 on branch maint/1.10 (BUG: Fix bug with reading old reports)
  doc/changes/devel/13341.bugfix.rst
  mne/report/report.py
  mne/report/tests/test_report.py
Labels: backport-candidate

#13345 MAINT: Restore statsmodels to pip-pre
  tools/install_pre_requirements.sh
Labels: no-changelog-entry-needed

#13340 Capitalize Get Help
  doc/index.rst
Labels: DOC, no-changelog-entry-needed

#13346 BUG: Fix GED tolerances and improve cov validation
  mne/decoding/_ged.py
  mne/decoding/base.py
  mne/decoding/tests/test_ged.py
Labels: no-changelog-entry-needed

#13349 Rename devel to dev
  .github/workflows/check_changelog.yml
  doc/Makefile
  doc/_static/versions.json
  doc/changes/dev.rst
  doc/changes/dev.rst.template
  doc/changes/dev/.gitignore
  doc/changes/dev/13112.bugfix.rst
  doc/changes/dev/13259.newfeature.rst
  doc/changes/dev/13341.bugfix.rst
  doc/conf.py
  doc/development/contributing.rst
  doc/development/whats_new.rst
  doc/sphinxext/credit_tools.py
  mne/utils/config.py
  mne/utils/tests/test_config.py
  pyproject.toml
Labels: no-changelog-entry-needed

#13351 MAINT: Fix CircleCI
  mne/utils/misc.py
  tutorials/preprocessing/70_fnirs_processing.py
Labels: no-changelog-entry-needed

#13356 Update license fields
  pyproject.toml
Labels: no-changelog-entry-needed
