Repository mne-tools/mne-python, pull requests merged in 2025-01, with the labels that each got.

#13046 DOC: Update file naming conventions for DigMontage and fix typos
  doc/changes/v1.7.rst
  doc/changes/v1.9.rst
  mne/channels/montage.py
Labels: no-changelog-entry-needed, skip-changelog-checks

#13049 Fix deprecation warnings with newer versions of dependencies.
  .circleci/config.yml
  .github/workflows/tests.yml
  doc/conf.py
  doc/development/contributing.rst
  doc/install/installers.rst
  environment.yml
  mne/conftest.py
  mne/datasets/sleep_physionet/_utils.py
  mne/decoding/base.py
  mne/decoding/transformer.py
  mne/export/tests/test_export.py
  mne/fixes.py
  mne/preprocessing/maxwell.py
  mne/preprocessing/tests/test_maxwell.py
  mne/transforms.py
  tools/github_actions_dependencies.sh
  tools/hooks/update_environment_file.py
  tools/install_pre_requirements.sh
Labels: MAINT, no-changelog-entry-needed

#13048 `plot_evoked_field`: fix not being able to tweak the `vmin`/`vmax` of the field lines when `plot_density=False`
  doc/changes/devel/13048.bugfix.rst
  mne/viz/evoked_field.py
Labels: BUG, VIZ

#13053 MAINT: Ensure limited set of tests are skipped
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  azure-pipelines.yml
  environment.yml
  mne/conftest.py
  mne/decoding/tests/test_ssd.py
  mne/tests/test_parallel.py
  mne/viz/_brain/tests/test_brain.py
  mne/viz/tests/test_evoked.py
  mne/viz/tests/test_raw.py
  pyproject.toml
  tools/azure_dependencies.sh
  tools/get_minimal_commands.sh
  tools/get_testing_version.sh
  tools/github_actions_env_vars.sh
  tools/github_actions_test.sh
  tools/hooks/update_environment_file.py
  tools/install_pre_requirements.sh
Labels: no-changelog-entry-needed

#13056 BUG: Fix bug with helium anon
  doc/changes/devel/13056.bugfix.rst
  mne/_fiff/meas_info.py
  mne/_fiff/tests/test_meas_info.py
  mne/_fiff/write.py
  mne/utils/_testing.py
Labels: backport-candidate

#13051 [DOC] extend documentation for add_channels
  mne/channels/channels.py
Labels: no-changelog-entry-needed

#13061 Backport PR #13056 on branch maint/1.9 (BUG: Fix bug with helium anon)
  doc/changes/devel/13056.bugfix.rst
  mne/_fiff/meas_info.py
  mne/_fiff/tests/test_meas_info.py
  mne/_fiff/write.py
  mne/utils/_testing.py
Labels: backport-candidate

#13062 BUG: Fix bug with interval calculation
  azure-pipelines.yml
  doc/changes/devel/13062.bugfix.rst
  mne/preprocessing/_fine_cal.py
  mne/preprocessing/tests/test_fine_cal.py
Labels: backport-candidate

#13067 [BUG] Fix taper weighting in computation of TFR multitaper power
  doc/changes/devel/13067.bugfix.rst
  mne/time_frequency/tests/test_tfr.py
  mne/time_frequency/tfr.py
Labels: backport-candidate

#13075 MAINT: Add Numba to 3.13 test
  doc/changes/devel/12656.bugfix.rst
  mne/export/_export.py
  mne/forward/tests/test_make_forward.py
  mne/preprocessing/tests/test_fine_cal.py
  mne/utils/docs.py
  tools/github_actions_dependencies.sh
  tools/github_actions_env_vars.sh
Labels: no-changelog-entry-needed, skip-changelog-checks

#13076 MAINT: Fix doc build
  doc/sphinxext/mne_doc_utils.py
  doc/sphinxext/related_software.py
  mne/viz/backends/_pyvista.py
  tools/circleci_dependencies.sh
  tutorials/intro/70_report.py
  tutorials/inverse/20_dipole_fit.py
Labels: backport-candidate, no-changelog-entry-needed

#13077 Backport PR #13076 on branch maint/1.9 (MAINT: Fix doc build)
  doc/sphinxext/mne_doc_utils.py
  doc/sphinxext/related_software.py
  tools/circleci_dependencies.sh
  tutorials/intro/70_report.py
  tutorials/inverse/20_dipole_fit.py
Labels: backport-candidate, no-changelog-entry-needed

#12071 Allow lasso selection sensors in a plot_evoked_topo
  doc/changes/devel/12071.newfeature.rst
  mne/epochs.py
  mne/evoked.py
  mne/viz/_figure.py
  mne/viz/_mpl_figure.py
  mne/viz/evoked.py
  mne/viz/tests/test_raw.py
  mne/viz/tests/test_topo.py
  mne/viz/tests/test_utils.py
  mne/viz/topo.py
  mne/viz/ui_events.py
  mne/viz/utils.py
Labels: ENH

#13070 BUGFIX: return events if provided when current = desired sfreq
  doc/changes/devel/13070.bugfix.rst
  doc/changes/names.inc
  mne/io/base.py
  mne/io/fiff/tests/test_raw_fiff.py
Labels: backport-candidate

#13081 Backport PR #13070 on branch maint/1.9 (BUGFIX: return events if provided when current = desired sfreq)
  doc/changes/devel/13070.bugfix.rst
  doc/changes/names.inc
  mne/io/base.py
  mne/io/fiff/tests/test_raw_fiff.py
Labels: backport-candidate

#13082 BUG: Fix bug with Mesa 3D detection
  doc/changes/devel/13082.bugfix.rst
  examples/preprocessing/movement_detection.py
  mne/conftest.py
  mne/viz/_brain/tests/test_brain.py
  mne/viz/backends/_pyvista.py
Labels: backport-candidate

#13084 Backport PR #13082 on branch maint/1.9 (BUG: Fix bug with Mesa 3D detection)
  doc/changes/devel/13082.bugfix.rst
  examples/preprocessing/movement_detection.py
  mne/conftest.py
  mne/viz/_brain/tests/test_brain.py
  mne/viz/backends/_pyvista.py
Labels: backport-candidate

#13086 Fix _close() on MNEAnnotationsFigure and MNESelectionFigure
  mne/viz/_mpl_figure.py
  tutorials/epochs/60_make_fixed_length_epochs.py
Labels: no-changelog-entry-needed
