Repository mne-tools/mne-python, pull requests merged in 2025-02, with the labels that each got.

#13101 Take units (m or mm) into account when showing fieldmaps on top of brains
  azure-pipelines.yml
  doc/changes/devel/13101.bugfix.rst
  mne/conftest.py
  mne/viz/evoked_field.py
  mne/viz/tests/test_3d.py
Labels: BUG

#13106 MAINT: Use statsmodels pre and fix CircleCI
  doc/sphinxext/related_software.py
  tools/install_pre_requirements.sh
Labels: no-changelog-entry-needed

#13083 BUG: Fix bug with reading dig strings
  doc/changes/devel/13083.bugfix.rst
  mne/_fiff/_digitization.py
  mne/_fiff/meas_info.py
  mne/_fiff/open.py
  mne/_fiff/tag.py
  mne/_fiff/tests/test_meas_info.py
Labels: backport-candidate

#13114 Backport PR #13083 on branch maint/1.9 (BUG: Fix bug with reading dig strings)
  doc/changes/devel/13083.bugfix.rst
  mne/_fiff/_digitization.py
  mne/_fiff/meas_info.py
  mne/_fiff/open.py
  mne/_fiff/tag.py
  mne/_fiff/tests/test_meas_info.py
Labels: backport-candidate

#13129 BUG: Fix bug with coord frame reading
  mne/_fiff/_digitization.py
  mne/_fiff/constants.py
  mne/_fiff/tests/test_constants.py
  mne/channels/tests/test_montage.py
  mne/transforms.py
Labels: no-changelog-entry-needed

#13132 BUG: Fix bug with movecomp and t=0
  examples/preprocessing/movement_compensation.py
  examples/preprocessing/otp.py
  mne/preprocessing/maxwell.py
  mne/preprocessing/tests/test_maxwell.py
  tutorials/inverse/85_brainstorm_phantom_ctf.py
Labels: no-changelog-entry-needed

#13134 MAINT: Update towncrier dep
  pyproject.toml
Labels: no-changelog-entry-needed
